image:
  file: .gitpod.Dockerfile

workspaceLocation: tour/main.code-workspace # Relative to /workspace dir

ports:
  - port: 1024-6000
    onOpen: ignore

tasks:
  - name: Build Đ Tooling
    command: |
      # update packages in root epm home
      cd $HOME/edh/edh-universe
      epm up
      epm i
      epm x gen-hie > hie.yaml
      # update executables from Edh packages
      stack update
      stack install

vscode:
  extensions:
    - justusadam.language-haskell
    - haskell.haskell
    - complyue.edh-vscode-syntax
    - complyue.edh-vscode-formatter
    - complyue.edh-vscode-pack
    - complyue.edh-vscode-lsc
    - complyue.haskit-vscode
