image:
  file: .gitpod.Dockerfile

ports:
  - port: 1024-6000
    onOpen: ignore

tasks:
  - name: Build Đ Tooling
    init: |
      # prepare user local bin, add to PATH
      mkdir -p ~/.local/bin
      echo 'export PATH=$(cd ~/.local/bin; pwd):"$PATH"' > ~/.bashrc.d/999-usr-local
      . ~/.bashrc.d/999-usr-local
      # install epm
      curl -o ~/.local/bin/epm -L https://github.com/e-wrks/epm/raw/latest/epm
      chmod a+x ~/.local/bin/epm
      # prepare /workspace as an epm home
      cd /workspace
      epm init \
       -B https://github.com/e-wrks \
        edh \
       -B http://github.com/complyue \
        nedh els sedh hasdim haskit
      cd /workspace/edh-universe
      # do HLS a favor
      stack install implicit-hie
      epm x gen-hie > hie.yaml
      # build & install executables from Edh packages
      stack update
      stack install
    command: |
      cd /workspace/edh-universe
      epm up
      epm i
      epm x gen-hie > hie.yaml
      stack update
      stack install
      gp open '/workspace/tour/welcome.edh'

vscode:
  extensions:
    - justusadam.language-haskell
    - haskell.haskell
    - complyue.edh-vscode-syntax
    - complyue.edh-vscode-formatter
    - complyue.edh-vscode-pack
    - complyue.edh-vscode-lsc
    - complyue.haskit-vscode
